import * as t from "io-ts";

// Generated with ts-to-io
// Command: npx ts-to-io types/index.ts --follow-imports

export const TSlideData = t.type({
  code: t.string,
  thumbnail: t.string,
  animations: t.type({
    move: t.type({
      duration: t.number,
      ease: t.keyof({
        linear: null,
        "linear(x1, x2 25%, x3)": null,
        in: null,
        out: null,
        inOut: null,
        inQuad: null,
        outQuad: null,
        inOutQuad: null,
        inCubic: null,
        outCubic: null,
        inOutCubic: null,
        inQuart: null,
        outQuart: null,
        inOutQuart: null,
        inQuint: null,
        outQuint: null,
        inOutQuint: null,
        inSine: null,
        outSine: null,
        inOutSine: null,
        inCirc: null,
        outCirc: null,
        inOutCirc: null,
        inExpo: null,
        outExpo: null,
        inOutExpo: null,
        inBounce: null,
        outBounce: null,
        inOutBounce: null,
        inBack: null,
        outBack: null,
        inOutBack: null,
        inElastic: null,
        outElastic: null,
        inOutElastic: null,
        irregular: null,
        cubicBezier: null,
        steps: null,
        "in(p = 1.675)": null,
        "out(p = 1.675)": null,
        "inOut(p = 1.675)": null,
        "inBack(overshoot = 1.70158)": null,
        "outBack(overshoot = 1.70158)": null,
        "inOutBack(overshoot = 1.70158)": null,
        "inElastic(amplitude = 1, period = .3)": null,
        "outElastic(amplitude = 1, period = .3)": null,
        "inOutElastic(amplitude = 1, period = .3)": null,
        "irregular(length = 10, randomness = 1)": null,
        "cubicBezier(x1, y1, x2, y2)": null,
        "steps(steps = 10)": null,
      }),
    }),
    fade: t.type({
      duration: t.number,
      ease: t.keyof({
        linear: null,
        "linear(x1, x2 25%, x3)": null,
        in: null,
        out: null,
        inOut: null,
        inQuad: null,
        outQuad: null,
        inOutQuad: null,
        inCubic: null,
        outCubic: null,
        inOutCubic: null,
        inQuart: null,
        outQuart: null,
        inOutQuart: null,
        inQuint: null,
        outQuint: null,
        inOutQuint: null,
        inSine: null,
        outSine: null,
        inOutSine: null,
        inCirc: null,
        outCirc: null,
        inOutCirc: null,
        inExpo: null,
        outExpo: null,
        inOutExpo: null,
        inBounce: null,
        outBounce: null,
        inOutBounce: null,
        inBack: null,
        outBack: null,
        inOutBack: null,
        inElastic: null,
        outElastic: null,
        inOutElastic: null,
        irregular: null,
        cubicBezier: null,
        steps: null,
        "in(p = 1.675)": null,
        "out(p = 1.675)": null,
        "inOut(p = 1.675)": null,
        "inBack(overshoot = 1.70158)": null,
        "outBack(overshoot = 1.70158)": null,
        "inOutBack(overshoot = 1.70158)": null,
        "inElastic(amplitude = 1, period = .3)": null,
        "outElastic(amplitude = 1, period = .3)": null,
        "inOutElastic(amplitude = 1, period = .3)": null,
        "irregular(length = 10, randomness = 1)": null,
        "cubicBezier(x1, y1, x2, y2)": null,
        "steps(steps = 10)": null,
      }),
    }),
  }),
});
