export default [
  { id: "abap", label: "ABAP" },
  { id: "abnf", label: "ABNF" },
  { id: "actionscript", label: "ActionScript" },
  { id: "ada", label: "Ada" },
  { id: "agda", label: "Agda" },
  { id: "al", label: "AL" },
  { id: "antlr4", label: "ANTLR4" },
  { id: "apacheconf", label: "Apache Configuration" },
  { id: "apex", label: "Apex" },
  { id: "apl", label: "APL" },
  { id: "applescript", label: "AppleScript" },
  { id: "aql", label: "AQL" },
  { id: "arduino", label: "Arduino" },
  { id: "arff", label: "ARFF" },
  { id: "arm-asm", label: "ARM Assembly" },
  { id: "arturo", label: "Arturo" },
  { id: "asciidoc", label: "AsciiDoc" },
  { id: "asm6502", label: "6502 Assembly" },
  { id: "asmatmel", label: "Atmel AVR Assembly" },
  { id: "aspnet", label: "ASP.NET (C#)" },
  { id: "atom", label: "Atom" },
  { id: "autohotkey", label: "AutoHotKey" },
  { id: "autoit", label: "AutoIt" },
  { id: "avisynth", label: "AviSynth" },
  { id: "avro-idl", label: "Avro IDL" },
  { id: "awk", label: "AWK" },
  { id: "bash", label: "Bash" },
  { id: "basic", label: "BASIC" },
  { id: "batch", label: "Batch" },
  { id: "bbcode", label: "BBcode" },
  { id: "bbj", label: "BBj" },
  { id: "bicep", label: "Bicep" },
  { id: "birb", label: "Birb" },
  { id: "bison", label: "Bison" },
  { id: "bnf", label: "BNF" },
  { id: "bqn", label: "BQN" },
  { id: "brainfuck", label: "Brainfuck" },
  { id: "brightscript", label: "BrightScript" },
  { id: "bro", label: "Bro" },
  { id: "bsl", label: "BSL" },
  { id: "c", label: "C" },
  { id: "cfscript", label: "CFScript" },
  { id: "chaiscript", label: "ChaiScript" },
  { id: "cil", label: "CIL" },
  { id: "cilk-c", label: "Cilk/C" },
  { id: "cilk-cpp", label: "Cilk/C++" },
  { id: "clike", label: "C-Like" },
  { id: "clojure", label: "Clojure" },
  { id: "cmake", label: "CMake" },
  { id: "cobol", label: "COBOL" },
  { id: "coffeescript", label: "CoffeeScript" },
  { id: "concurnas", label: "Concurnas" },
  { id: "cooklang", label: "Cooklang" },
  { id: "coq", label: "Coq" },
  { id: "cpp", label: "C++" },
  { id: "crystal", label: "Crystal" },
  { id: "csharp", label: "C#" },
  { id: "csp", label: "Content-Security-Policy" },
  { id: "css", label: "CSS" },
  { id: "css-extras", label: "CSS Extras" },
  { id: "csv", label: "CSV" },
  { id: "cue", label: "CUE" },
  { id: "cypher", label: "Cypher" },
  { id: "d", label: "D" },
  { id: "dart", label: "Dart" },
  { id: "dataweave", label: "DataWeave" },
  { id: "dax", label: "DAX" },
  { id: "dhall", label: "Dhall" },
  { id: "diff", label: "Diff" },
  { id: "django", label: "Django/Jinja2" },
  { id: "dns-zone-file", label: "DNS zone file" },
  { id: "docker", label: "Docker" },
  { id: "dot", label: "DOT (Graphviz)" },
  { id: "ebnf", label: "EBNF" },
  { id: "editorconfig", label: "EditorConfig" },
  { id: "eiffel", label: "Eiffel" },
  { id: "ejs", label: "EJS" },
  { id: "elixir", label: "Elixir" },
  { id: "elm", label: "Elm" },
  { id: "erb", label: "ERB" },
  { id: "erlang", label: "Erlang" },
  { id: "etlua", label: "Embedded Lua templating" },
  { id: "excel-formula", label: "Excel Formula" },
  { id: "factor", label: "Factor" },
  { id: "false", label: "False" },
  { id: "firestore-security-rules", label: "Firestore security rules" },
  { id: "flow", label: "Flow" },
  { id: "fortran", label: "Fortran" },
  { id: "fsharp", label: "F#" },
  { id: "ftl", label: "FreeMarker Template Language" },
  { id: "gamemakerlanguage", label: "GameMaker Language" },
  { id: "gap", label: "GAP (CAS)" },
  { id: "gcode", label: "G-code" },
  { id: "gdscript", label: "GDScript" },
  { id: "gedcom", label: "GEDCOM" },
  { id: "gettext", label: "gettext" },
  { id: "gherkin", label: "Gherkin" },
  { id: "git", label: "Git" },
  { id: "glsl", label: "GLSL" },
  { id: "gn", label: "GN" },
  { id: "go", label: "Go" },
  { id: "go-module", label: "Go module" },
  { id: "gradle", label: "Gradle" },
  { id: "graphql", label: "GraphQL" },
  { id: "groovy", label: "Groovy" },
  { id: "haml", label: "Haml" },
  { id: "handlebars", label: "Handlebars" },
  { id: "haskell", label: "Haskell" },
  { id: "haxe", label: "Haxe" },
  { id: "hcl", label: "HCL" },
  { id: "hlsl", label: "HLSL" },
  { id: "hoon", label: "Hoon" },
  { id: "hpkp", label: "HTTP Public-Key-Pins" },
  { id: "hsts", label: "HTTP Strict-Transport-Security" },
  { id: "html", label: "HTML" },
  { id: "http", label: "HTTP" },
  { id: "ichigojam", label: "IchigoJam" },
  { id: "icon", label: "Icon" },
  { id: "icu-message-format", label: "ICU Message Format" },
  { id: "idris", label: "Idris" },
  { id: "iecst", label: "Structured Text (IEC 61131-3)" },
  { id: "ignore", label: ".ignore" },
  { id: "inform7", label: "Inform 7" },
  { id: "ini", label: "Ini" },
  { id: "io", label: "Io" },
  { id: "j", label: "J" },
  { id: "java", label: "Java" },
  { id: "javadoc", label: "JavaDoc" },
  { id: "javadoclike", label: "JavaDoc-like" },
  { id: "javascript", label: "JavaScript" },
  { id: "javastacktrace", label: "Java stack trace" },
  { id: "jexl", label: "Jexl" },
  { id: "jolie", label: "Jolie" },
  { id: "jq", label: "JQ" },
  { id: "js-extras", label: "JS Extras" },
  { id: "js-templates", label: "JS Templates" },
  { id: "jsdoc", label: "JSDoc" },
  { id: "json", label: "JSON" },
  { id: "json5", label: "JSON5" },
  { id: "jsonp", label: "JSONP" },
  { id: "jsstacktrace", label: "JS stack trace" },
  { id: "jsx", label: "React JSX" },
  { id: "julia", label: "Julia" },
  { id: "keepalived", label: "Keepalived Configure" },
  { id: "keyman", label: "Keyman" },
  { id: "kotlin", label: "Kotlin" },
  { id: "kumir", label: "KuMir (КуМир)" },
  { id: "kusto", label: "Kusto" },
  { id: "latex", label: "LaTeX" },
  { id: "latte", label: "Latte" },
  { id: "ld", label: "GNU Linker Script" },
  { id: "less", label: "Less" },
  { id: "lilypond", label: "LilyPond" },
  { id: "liquid", label: "Liquid" },
  { id: "lisp", label: "Lisp" },
  { id: "livescript", label: "LiveScript" },
  { id: "llvm", label: "LLVM IR" },
  { id: "log", label: "Log file" },
  { id: "lolcode", label: "LOLCODE" },
  { id: "lua", label: "Lua" },
  { id: "magma", label: "Magma (CAS)" },
  { id: "makefile", label: "Makefile" },
  { id: "markdown", label: "Markdown" },
  { id: "markup-templating", label: "Markup Templating" },
  { id: "mata", label: "Mata" },
  { id: "mathml", label: "MathML" },
  { id: "matlab", label: "MATLAB" },
  { id: "maxscript", label: "MAXScript" },
  { id: "mel", label: "MEL" },
  { id: "mermaid", label: "Mermaid" },
  { id: "metafont", label: "METAFONT" },
  { id: "mizar", label: "Mizar" },
  { id: "mongodb", label: "MongoDB" },
  { id: "monkey", label: "Monkey" },
  { id: "moonscript", label: "MoonScript" },
  { id: "n1ql", label: "N1QL" },
  { id: "n4js", label: "N4JS" },
  { id: "nand2tetris-hdl", label: "Nand To Tetris HDL" },
  { id: "naniscript", label: "Naninovel Script" },
  { id: "nasm", label: "NASM" },
  { id: "neon", label: "NEON" },
  { id: "nevod", label: "Nevod" },
  { id: "nginx", label: "nginx" },
  { id: "nim", label: "Nim" },
  { id: "nix", label: "Nix" },
  { id: "nsis", label: "NSIS" },
  { id: "objectivec", label: "Objective-C" },
  { id: "ocaml", label: "OCaml" },
  { id: "odin", label: "Odin" },
  { id: "opencl", label: "OpenCL" },
  { id: "openqasm", label: "OpenQasm" },
  { id: "oz", label: "Oz" },
  { id: "parigp", label: "PARI/GP" },
  { id: "parser", label: "Parser" },
  { id: "pascal", label: "Pascal" },
  { id: "pascaligo", label: "Pascaligo" },
  { id: "pcaxis", label: "PC-Axis" },
  { id: "peoplecode", label: "PeopleCode" },
  { id: "perl", label: "Perl" },
  { id: "php", label: "PHP" },
  { id: "php-extras", label: "PHP Extras" },
  { id: "phpdoc", label: "PHPDoc" },
  { id: "plantuml", label: "PlantUML" },
  { id: "plsql", label: "PL/SQL" },
  { id: "powerquery", label: "PowerQuery" },
  { id: "powershell", label: "PowerShell" },
  { id: "processing", label: "Processing" },
  { id: "prolog", label: "Prolog" },
  { id: "promql", label: "PromQL" },
  { id: "properties", label: ".properties" },
  { id: "protobuf", label: "Protocol Buffers" },
  { id: "psl", label: "PATROL Scripting Language" },
  { id: "pug", label: "Pug" },
  { id: "puppet", label: "Puppet" },
  { id: "pure", label: "Pure" },
  { id: "purebasic", label: "PureBasic" },
  { id: "purescript", label: "PureScript" },
  { id: "python", label: "Python" },
  { id: "q", label: "Q (kdb+ database)" },
  { id: "qml", label: "QML" },
  { id: "qore", label: "Qore" },
  { id: "qsharp", label: "Q#" },
  { id: "r", label: "R" },
  { id: "racket", label: "Racket" },
  { id: "razor", label: "Razor C#" },
  { id: "reason", label: "Reason" },
  { id: "regex", label: "Regex" },
  { id: "rego", label: "Rego" },
  { id: "renpy", label: "Ren'py" },
  { id: "rescript", label: "ReScript" },
  { id: "rest", label: "reST (reStructuredText)" },
  { id: "rip", label: "Rip" },
  { id: "roboconf", label: "Roboconf" },
  { id: "robotframework", label: "Robot Framework" },
  { id: "rss", label: "RSS" },
  { id: "ruby", label: "Ruby" },
  { id: "rust", label: "Rust" },
  { id: "sas", label: "SAS" },
  { id: "sass", label: "Sass (Sass)" },
  { id: "scala", label: "Scala" },
  { id: "scheme", label: "Scheme" },
  { id: "scss", label: "Sass (SCSS)" },
  { id: "shell-session", label: "Shell Session" },
  { id: "smali", label: "Smali" },
  { id: "smalltalk", label: "Smalltalk" },
  { id: "smarty", label: "Smarty" },
  { id: "sml", label: "SML" },
  { id: "solidity", label: "Solidity (Ethereum)" },
  { id: "solution-file", label: "Solution file" },
  { id: "soy", label: "Soy (Closure Template)" },
  { id: "sparql", label: "SPARQL" },
  { id: "splunk-spl", label: "Splunk SPL" },
  { id: "sqf", label: "SQF: Status Quo Function (Arma 3)" },
  { id: "sql", label: "SQL" },
  { id: "squirrel", label: "Squirrel" },
  { id: "ssml", label: "SSML" },
  { id: "stan", label: "Stan" },
  { id: "stata", label: "Stata Ado" },
  { id: "stylus", label: "Stylus" },
  { id: "supercollider", label: "SuperCollider" },
  { id: "svg", label: "SVG" },
  { id: "swift", label: "Swift" },
  { id: "systemd", label: "Systemd configuration file" },
  { id: "t4-cs", label: "T4 Text Templates (C#)" },
  { id: "t4-templating", label: "T4 templating" },
  { id: "t4-vb", label: "T4 Text Templates (VB)" },
  { id: "tap", label: "TAP" },
  { id: "tcl", label: "Tcl" },
  { id: "textile", label: "Textile" },
  { id: "toml", label: "TOML" },
  { id: "tremor", label: "Tremor" },
  { id: "tsx", label: "React TSX" },
  { id: "tt2", label: "Template Toolkit 2" },
  { id: "turtle", label: "Turtle" },
  { id: "twig", label: "Twig" },
  { id: "typescript", label: "TypeScript" },
  { id: "typoscript", label: "TypoScropt" },
  { id: "unrealscript", label: "UnrealScript" },
  { id: "uorazor", label: "UO Razor Script" },
  { id: "uri", label: "URI" },
  { id: "v", label: "V" },
  { id: "vala", label: "Vala" },
  { id: "vbnet", label: "VB.net" },
  { id: "velocity", label: "Velocity" },
  { id: "verilog", label: "Verilog" },
  { id: "vhdl", label: "VHDL" },
  { id: "vim", label: "vim" },
  { id: "visual-basic", label: "Visual Basic" },
  { id: "warpscript", label: "WarpScript" },
  { id: "wasm", label: "WebAssembly" },
  { id: "webidl", label: "Web IDL" },
  { id: "wiki", label: "Wiki markup" },
  { id: "wolfram", label: "Wolfram language" },
  { id: "wqsl", label: "WGSL" },
  { id: "wren", label: "Wren" },
  { id: "xeora", label: "Xeora" },
  { id: "xml", label: "XML" },
  { id: "xml-doc", label: "XML doc (.net)" },
  { id: "xojo", label: "Xojo (REALbasic)" },
  { id: "xquery", label: "XQuery" },
  { id: "yaml", label: "YAML" },
  { id: "yang", label: "YANG" },
  { id: "zig", label: "Zig" },
];
