export default [
  { value: "abap", label: "ABAP" },
  { value: "abnf", label: "ABNF" },
  { value: "actionscript", label: "ActionScript" },
  { value: "ada", label: "Ada" },
  { value: "agda", label: "Agda" },
  { value: "al", label: "AL" },
  { value: "antlr4", label: "ANTLR4" },
  { value: "apacheconf", label: "Apache Configuration" },
  { value: "apex", label: "Apex" },
  { value: "apl", label: "APL" },
  { value: "applescript", label: "AppleScript" },
  { value: "aql", label: "AQL" },
  { value: "arduino", label: "Arduino" },
  { value: "arff", label: "ARFF" },
  { value: "arm-asm", label: "ARM Assembly" },
  { value: "arturo", label: "Arturo" },
  { value: "asciidoc", label: "AsciiDoc" },
  { value: "asm6502", label: "6502 Assembly" },
  { value: "asmatmel", label: "Atmel AVR Assembly" },
  { value: "aspnet", label: "ASP.NET (C#)" },
  { value: "atom", label: "Atom" },
  { value: "autohotkey", label: "AutoHotKey" },
  { value: "autoit", label: "AutoIt" },
  { value: "avisynth", label: "AviSynth" },
  { value: "avro-idl", label: "Avro IDL" },
  { value: "awk", label: "AWK" },
  { value: "bash", label: "Bash" },
  { value: "basic", label: "BASIC" },
  { value: "batch", label: "Batch" },
  { value: "bbcode", label: "BBcode" },
  { value: "bbj", label: "BBj" },
  { value: "bicep", label: "Bicep" },
  { value: "birb", label: "Birb" },
  { value: "bison", label: "Bison" },
  { value: "bnf", label: "BNF" },
  { value: "bqn", label: "BQN" },
  { value: "brainfuck", label: "Brainfuck" },
  { value: "brightscript", label: "BrightScript" },
  { value: "bro", label: "Bro" },
  { value: "bsl", label: "BSL" },
  { value: "c", label: "C" },
  { value: "cfscript", label: "CFScript" },
  { value: "chaiscript", label: "ChaiScript" },
  { value: "cil", label: "CIL" },
  { value: "cilk-c", label: "Cilk/C" },
  { value: "cilk-cpp", label: "Cilk/C++" },
  { value: "clike", label: "C-Like" },
  { value: "clojure", label: "Clojure" },
  { value: "cmake", label: "CMake" },
  { value: "cobol", label: "COBOL" },
  { value: "coffeescript", label: "CoffeeScript" },
  { value: "concurnas", label: "Concurnas" },
  { value: "cooklang", label: "Cooklang" },
  { value: "coq", label: "Coq" },
  { value: "cpp", label: "C++" },
  { value: "crystal", label: "Crystal" },
  { value: "csharp", label: "C#" },
  { value: "csp", label: "Content-Security-Policy" },
  { value: "css", label: "CSS" },
  { value: "css-extras", label: "CSS Extras" },
  { value: "csv", label: "CSV" },
  { value: "cue", label: "CUE" },
  { value: "cypher", label: "Cypher" },
  { value: "d", label: "D" },
  { value: "dart", label: "Dart" },
  { value: "dataweave", label: "DataWeave" },
  { value: "dax", label: "DAX" },
  { value: "dhall", label: "Dhall" },
  { value: "diff", label: "Diff" },
  { value: "django", label: "Django/Jinja2" },
  { value: "dns-zone-file", label: "DNS zone file" },
  { value: "docker", label: "Docker" },
  { value: "dot", label: "DOT (Graphviz)" },
  { value: "ebnf", label: "EBNF" },
  { value: "editorconfig", label: "EditorConfig" },
  { value: "eiffel", label: "Eiffel" },
  { value: "ejs", label: "EJS" },
  { value: "elixir", label: "Elixir" },
  { value: "elm", label: "Elm" },
  { value: "erb", label: "ERB" },
  { value: "erlang", label: "Erlang" },
  { value: "etlua", label: "Embedded Lua templating" },
  { value: "excel-formula", label: "Excel Formula" },
  { value: "factor", label: "Factor" },
  { value: "false", label: "False" },
  { value: "firestore-security-rules", label: "Firestore security rules" },
  { value: "flow", label: "Flow" },
  { value: "fortran", label: "Fortran" },
  { value: "fsharp", label: "F#" },
  { value: "ftl", label: "FreeMarker Template Language" },
  { value: "gamemakerlanguage", label: "GameMaker Language" },
  { value: "gap", label: "GAP (CAS)" },
  { value: "gcode", label: "G-code" },
  { value: "gdscript", label: "GDScript" },
  { value: "gedcom", label: "GEDCOM" },
  { value: "gettext", label: "gettext" },
  { value: "gherkin", label: "Gherkin" },
  { value: "git", label: "Git" },
  { value: "glsl", label: "GLSL" },
  { value: "gn", label: "GN" },
  { value: "go", label: "Go" },
  { value: "go-module", label: "Go module" },
  { value: "gradle", label: "Gradle" },
  { value: "graphql", label: "GraphQL" },
  { value: "groovy", label: "Groovy" },
  { value: "haml", label: "Haml" },
  { value: "handlebars", label: "Handlebars" },
  { value: "haskell", label: "Haskell" },
  { value: "haxe", label: "Haxe" },
  { value: "hcl", label: "HCL" },
  { value: "hlsl", label: "HLSL" },
  { value: "hoon", label: "Hoon" },
  { value: "hpkp", label: "HTTP Public-Key-Pins" },
  { value: "hsts", label: "HTTP Strict-Transport-Security" },
  { value: "html", label: "HTML" },
  { value: "http", label: "HTTP" },
  { value: "ichigojam", label: "IchigoJam" },
  { value: "icon", label: "Icon" },
  { value: "icu-message-format", label: "ICU Message Format" },
  { value: "idris", label: "Idris" },
  { value: "iecst", label: "Structured Text (IEC 61131-3)" },
  { value: "ignore", label: ".ignore" },
  { value: "inform7", label: "Inform 7" },
  { value: "ini", label: "Ini" },
  { value: "io", label: "Io" },
  { value: "j", label: "J" },
  { value: "java", label: "Java" },
  { value: "javadoc", label: "JavaDoc" },
  { value: "javadoclike", label: "JavaDoc-like" },
  { value: "javascript", label: "JavaScript" },
  { value: "javastacktrace", label: "Java stack trace" },
  { value: "jexl", label: "Jexl" },
  { value: "jolie", label: "Jolie" },
  { value: "jq", label: "JQ" },
  { value: "js-extras", label: "JS Extras" },
  { value: "js-templates", label: "JS Templates" },
  { value: "jsdoc", label: "JSDoc" },
  { value: "json", label: "JSON" },
  { value: "json5", label: "JSON5" },
  { value: "jsonp", label: "JSONP" },
  { value: "jsstacktrace", label: "JS stack trace" },
  { value: "jsx", label: "React JSX" },
  { value: "julia", label: "Julia" },
  { value: "keepalived", label: "Keepalived Configure" },
  { value: "keyman", label: "Keyman" },
  { value: "kotlin", label: "Kotlin" },
  { value: "kumir", label: "KuMir (КуМир)" },
  { value: "kusto", label: "Kusto" },
  { value: "latex", label: "LaTeX" },
  { value: "latte", label: "Latte" },
  { value: "ld", label: "GNU Linker Script" },
  { value: "less", label: "Less" },
  { value: "lilypond", label: "LilyPond" },
  { value: "liquvalue", label: "Liquvalue" },
  { value: "lisp", label: "Lisp" },
  { value: "livescript", label: "LiveScript" },
  { value: "llvm", label: "LLVM IR" },
  { value: "log", label: "Log file" },
  { value: "lolcode", label: "LOLCODE" },
  { value: "lua", label: "Lua" },
  { value: "magma", label: "Magma (CAS)" },
  { value: "makefile", label: "Makefile" },
  { value: "markdown", label: "Markdown" },
  { value: "markup-templating", label: "Markup Templating" },
  { value: "mata", label: "Mata" },
  { value: "mathml", label: "MathML" },
  { value: "matlab", label: "MATLAB" },
  { value: "maxscript", label: "MAXScript" },
  { value: "mel", label: "MEL" },
  { value: "mermavalue", label: "Mermavalue" },
  { value: "metafont", label: "METAFONT" },
  { value: "mizar", label: "Mizar" },
  { value: "mongodb", label: "MongoDB" },
  { value: "monkey", label: "Monkey" },
  { value: "moonscript", label: "MoonScript" },
  { value: "n1ql", label: "N1QL" },
  { value: "n4js", label: "N4JS" },
  { value: "nand2tetris-hdl", label: "Nand To Tetris HDL" },
  { value: "naniscript", label: "Naninovel Script" },
  { value: "nasm", label: "NASM" },
  { value: "neon", label: "NEON" },
  { value: "nevod", label: "Nevod" },
  { value: "nginx", label: "nginx" },
  { value: "nim", label: "Nim" },
  { value: "nix", label: "Nix" },
  { value: "nsis", label: "NSIS" },
  { value: "objectivec", label: "Objective-C" },
  { value: "ocaml", label: "OCaml" },
  { value: "odin", label: "Odin" },
  { value: "opencl", label: "OpenCL" },
  { value: "openqasm", label: "OpenQasm" },
  { value: "oz", label: "Oz" },
  { value: "parigp", label: "PARI/GP" },
  { value: "parser", label: "Parser" },
  { value: "pascal", label: "Pascal" },
  { value: "pascaligo", label: "Pascaligo" },
  { value: "pcaxis", label: "PC-Axis" },
  { value: "peoplecode", label: "PeopleCode" },
  { value: "perl", label: "Perl" },
  { value: "php", label: "PHP" },
  { value: "php-extras", label: "PHP Extras" },
  { value: "phpdoc", label: "PHPDoc" },
  { value: "plantuml", label: "PlantUML" },
  { value: "plsql", label: "PL/SQL" },
  { value: "powerquery", label: "PowerQuery" },
  { value: "powershell", label: "PowerShell" },
  { value: "processing", label: "Processing" },
  { value: "prolog", label: "Prolog" },
  { value: "promql", label: "PromQL" },
  { value: "properties", label: ".properties" },
  { value: "protobuf", label: "Protocol Buffers" },
  { value: "psl", label: "PATROL Scripting Language" },
  { value: "pug", label: "Pug" },
  { value: "puppet", label: "Puppet" },
  { value: "pure", label: "Pure" },
  { value: "purebasic", label: "PureBasic" },
  { value: "purescript", label: "PureScript" },
  { value: "python", label: "Python" },
  { value: "q", label: "Q (kdb+ database)" },
  { value: "qml", label: "QML" },
  { value: "qore", label: "Qore" },
  { value: "qsharp", label: "Q#" },
  { value: "r", label: "R" },
  { value: "racket", label: "Racket" },
  { value: "razor", label: "Razor C#" },
  { value: "reason", label: "Reason" },
  { value: "regex", label: "Regex" },
  { value: "rego", label: "Rego" },
  { value: "renpy", label: "Ren'py" },
  { value: "rescript", label: "ReScript" },
  { value: "rest", label: "reST (reStructuredText)" },
  { value: "rip", label: "Rip" },
  { value: "roboconf", label: "Roboconf" },
  { value: "robotframework", label: "Robot Framework" },
  { value: "rss", label: "RSS" },
  { value: "ruby", label: "Ruby" },
  { value: "rust", label: "Rust" },
  { value: "sas", label: "SAS" },
  { value: "sass", label: "Sass (Sass)" },
  { value: "scala", label: "Scala" },
  { value: "scheme", label: "Scheme" },
  { value: "scss", label: "Sass (SCSS)" },
  { value: "shell-session", label: "Shell Session" },
  { value: "smali", label: "Smali" },
  { value: "smalltalk", label: "Smalltalk" },
  { value: "smarty", label: "Smarty" },
  { value: "sml", label: "SML" },
  { value: "solidity", label: "Solidity (Ethereum)" },
  { value: "solution-file", label: "Solution file" },
  { value: "soy", label: "Soy (Closure Template)" },
  { value: "sparql", label: "SPARQL" },
  { value: "splunk-spl", label: "Splunk SPL" },
  { value: "sqf", label: "SQF: Status Quo Function (Arma 3)" },
  { value: "sql", label: "SQL" },
  { value: "squirrel", label: "Squirrel" },
  { value: "ssml", label: "SSML" },
  { value: "stan", label: "Stan" },
  { value: "stata", label: "Stata Ado" },
  { value: "stylus", label: "Stylus" },
  { value: "supercollider", label: "SuperCollider" },
  { value: "svg", label: "SVG" },
  { value: "swift", label: "Swift" },
  { value: "systemd", label: "Systemd configuration file" },
  { value: "t4-cs", label: "T4 Text Templates (C#)" },
  { value: "t4-templating", label: "T4 templating" },
  { value: "t4-vb", label: "T4 Text Templates (VB)" },
  { value: "tap", label: "TAP" },
  { value: "tcl", label: "Tcl" },
  { value: "textile", label: "Textile" },
  { value: "toml", label: "TOML" },
  { value: "tremor", label: "Tremor" },
  { value: "tsx", label: "React TSX" },
  { value: "tt2", label: "Template Toolkit 2" },
  { value: "turtle", label: "Turtle" },
  { value: "twig", label: "Twig" },
  { value: "typescript", label: "TypeScript" },
  { value: "typoscript", label: "TypoScropt" },
  { value: "unrealscript", label: "UnrealScript" },
  { value: "uorazor", label: "UO Razor Script" },
  { value: "uri", label: "URI" },
  { value: "v", label: "V" },
  { value: "vala", label: "Vala" },
  { value: "vbnet", label: "VB.net" },
  { value: "velocity", label: "Velocity" },
  { value: "verilog", label: "Verilog" },
  { value: "vhdl", label: "VHDL" },
  { value: "vim", label: "vim" },
  { value: "visual-basic", label: "Visual Basic" },
  { value: "warpscript", label: "WarpScript" },
  { value: "wasm", label: "WebAssembly" },
  { value: "webidl", label: "Web IDL" },
  { value: "wiki", label: "Wiki markup" },
  { value: "wolfram", label: "Wolfram language" },
  { value: "wqsl", label: "WGSL" },
  { value: "wren", label: "Wren" },
  { value: "xeora", label: "Xeora" },
  { value: "xml", label: "XML" },
  { value: "xml-doc", label: "XML doc (.net)" },
  { value: "xojo", label: "Xojo (REALbasic)" },
  { value: "xquery", label: "XQuery" },
  { value: "yaml", label: "YAML" },
  { value: "yang", label: "YANG" },
  { value: "zig", label: "Zig" },
];
